version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fishGame
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: admin # Суперпользователь
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: